version: '3.1'
services:
  springboot-app:
    container_name: springboot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - rabbitmq
    volumes:
      - app-data:/app/data

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  app-data:
  db-data:
